plugins:
  wootric_enabled:
    default: true
    client: true
  wootric_account_token:
    default: "Enter token"
    client: true
  wootric_customer_domain:
    default: "Example: discuss.example.com"
    client: true
  wootric_test_mode:
    default: false
    client: true